### ISSUE TITLE
Payment Screen for User Acceptance

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#102]
US: #101

Descrizione:
Quando l'utente accetta ci deve essere una schermata per il pagamento che al momento verrà gestito solo tramite saldo sull'app

**Comment by matteo-conti-97** [comment]
Questo si è manifestato tramite il bottone "Confirm and Pay" nel popup che viene generato quando si conferma un itinerario proposto, la gestione del pagamento viene fatta tramite la stored procedure "confirm_it" la quale conferma l'itinerario proposto esegue la stored procedure "pay" per aggiornare il saldo utente
