### ISSUE TITLE
RabbitMQ Development for Sending Data to MakeRouteService Microservice

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#107]
US: #105

Descrizione:
Sviluppare la parte di RabbitMQ che manda la roba al MakeRouteService

**Comment by matteo-conti-97** [comment]
Aggiunto il supporto a rabbitMQ in node-selector-service e in make-route-service, in particolare la connessione al broker di rabbitMQ, l'inizializzazione di una coda tra i due servizi e l'invio di un messaggio dummy in formato json, sarà poi da implementare in altri ticket lo scambio di messaggi veri tra i due microservizi.
