### ISSUE TITLE
Compatibility between nodes "booking" does not take date into consideration

### ISSUE THREAD

**Issue by StefanAdrianHuma** [LucaFalasca/Bus4You#128]
US: #2

Descrizione:

**Comment by LucaFalasca** [comment]
Non so se ci avevi già pensato, ma pensavo di gestire in questo modo la compatibilità temporale. 
Dati:
- X_i = ora di partenza del nodo i
- Y_i = ora di arrivo del nodo i
- D_ij = tempo di percorrenza dal nodo i al nodo j
- offset = indica un margine di tempo accettabile extra per D_ij (io metterei 15 minuti)

Compatibilità
- Se nodo1 ha l'arrivo all'ora Y_1 e il nodo2 ha la partenza all'ora X_2, saranno compatibili se D_12 < X_2 - Y_1 < D_12 + offest 
- Se nodo1 ha la partenza all'ora X_1 e il nodo2 ha la partenza all'ora X_2, saranno compatibili se D_12 < |X_2 - X_1| < D_12 + offest


@StefanAdrianHuma dimmi che ne pensi

**Comment by StefanAdrianHuma** [comment]
si puo fare!

**Comment by StefanAdrianHuma** [comment]
D_12 < X_2 - Y_1 < D_12 + offest
 D_12 < |X_2 - X_1| < D_12 + offest
 Dopo un consulto con Luca le formule sono state modificate in
 D_12 + offeset1 < |X_2 - X_1| < D_12 + offeset2
 D_12 + offset1 < X_2 - Y_1 < D_12 + offeset2
 con offeset1 quantita negativa che per il momento impostiamo 1 -5.

**Comment by StefanAdrianHuma** [comment]
Siano un nodo come "1S" dove il numero indica l'id del nodo mentre la lettera indica se è di tipo start 'S' o end 'E', mentre sia D_1S->2E come la distanza dal nodo di inizio di partenza all nodo di arrivo di fine usando il servizio ors.
Vanno studiati 4 possibili casi di compatibilità:

1) start->start
D = D_1S->2S
D - offset1 < |1S - 2S| < D + offest2

2) end->start
D = D_1E->2S
D - offset1 < |2S - 1E| < D + offest2

3) end->end
D = D_1E->2S + D_2S->2E
D - offset1 < |2E - 1E| < D + offest2

4) start->end
D = D_1S->1E + D_1E->2S + D_2S->2E
D - offset1 < |2S - 1E| < D + offest2

**Comment by StefanAdrianHuma** [comment]
offset1 = min(5, 0.15 * hour)
offset2 = min(10, 0.3 * hour)

**Comment by LucaFalasca** [comment]
@StefanAdrianHuma si può chiuedere questo ticket?
