### ISSUE TITLE
RabbitMq disconnects from clients due to not receiving heartbeats

### ISSUE THREAD

**Issue by matteo-conti-97** [LucaFalasca/Bus4You#141]
US: #73

Descrizione:
I servizi falliscono a pubblicare i dati su coda perchè rabbitMq uccide la connessione quando non li vede per x tempo

**Comment by matteo-conti-97** [comment]
Allungato il timeout dopo il quale il broker di rabbitMq considera la connessione "dead" dal default di 60 secondi a 3600 secondi (1 ora)

**Comment by LucaFalasca** [comment]
@matteo-conti-97 si può chiudere questo ticket?
