### ISSUE TITLE
get-token

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#185]
**Nome dell'Endpoint:** get-token

**Descrizione:** 
Genera un token necessario per l'utilizzo delle altre operazioni all'interno dell'API.

**URI della Risorsa:** 
`api/get_token`

**Tipo di Richiesta HTTP:** 
GET

**Content Type della Richiesta:** 
Nessuno

**Content Type della Risposta:** 
`application/json`

**Corpo della Richiesta:** 
Nessuno

**Parametri nel Percorso (Path Parameters):** 
Nessuno

**Parametri nella Query (Query Parameters):** 
Nessuno

**Corpo della Risposta:**

Codice Risposta HTTP 200 OK:
```json
{
  "status": "ok",
  "token": "valore-del-token"
}
```

Codice Risposta HTTP 400 Errore:
```json
{
  "status": "ERROR"
}
```

**Comment by matteo-conti-97** [comment]
Aggiunto un piccolo controllo per controllare che la connessione con il db non sia nulla
