### ISSUE TITLE
Configuring Docker Compose for communication between the BookingService microservice and the Neo4j

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#20]
US: #10 

Collegare con docker compose il microservizio al database

**Comment by LucaFalasca** [comment]
è stato messo Neo4J su docker compose, ma non funziona la comuncazione tra il booking-service e Neo4j. Da investigare

**Comment by matteo-conti-97** [comment]
Soluzione: 
-Modificato il docker-compose yml assegnando hostname al container neo4j e mettendo il flag "healtcheck" al servizio neo4j (richiesta della pagina web sulla porta 7474) 
-Aggiunto il flag "depends_on" con condizione "service_healthy" al servizio booking service che quindi attenderà che il servizio neo4j risulti "healthy" a seguito dell'healthcheck 
-Modificato, nel codice di BookingService.py,  l'uri per la connessione a neo4j come "neo4j://neo4jDb:7687" dove neo4jDb è l'hostname del container di neo4j, aggiunto il flag encrypted=false alla creazione del driver per la comunicazione con neo4j (probabilmente inutile)

**Comment by matteo-conti-97** [comment]
Soluzione:
-Modificato il docker-compose yml assegnando hostname al container neo4j e mettendo il flag "healtcheck" al servizio neo4j (richiesta della pagina web sulla porta 7474)
-Aggiunto il flag "depends_on" con condizione "service_healthy" al servizio booking service che quindi attenderà che il servizio neo4j risulti "healthy" a seguito dell'healthcheck
-Modificato, nel codice di BookingService.py, l'uri per la connessione a neo4j come "neo4j://neo4jDb:7687" dove neo4jDb è l'hostname del container di neo4j, aggiunto il flag encrypted=false alla creazione del driver per la comunicazione con neo4j (probabilmente inutile)
