### ISSUE TITLE
Create User Interface for Viewing Accepted Route Associated with Request

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#28]
US: #27

### Descrizione:
Fare l'UI dove l'utente può visualizzare la rotta associata ad una sua richiesta che è stata accettata

**Comment by matteo-conti-97** [comment]
Aggiunta la ui base.html che contiene una navbar e viene estesa da tutte le pagine html che richiedono di avere la navbar, aggiunto un prototipo di ui userRoutes.html in cui l'utente può vedere i percorsi presso i quali è prenotato ed i relativi dati, utilizzato bootstrap-italia per i css.

**Comment by matteo-conti-97** [comment]
Poi ditemi se vi piace, se ci sono cose che cambiereste, ma soprattutto che dati vogliamo visualizzare per i percorsi, se vogliamo vedere solo percorsi confermati o anche percorsi in attesa di conferma che verranno marchiati in modo diverso.

**Comment by LucaFalasca** [comment]
> Aggiunta la ui base.html che contiene una navbar e viene estesa da tutte le pagine html che richiedono di avere la navbar, aggiunto un prototipo di ui userRoutes.html in cui l'utente può vedere i percorsi presso i quali è prenotato ed i relativi dati, utilizzato bootstrap-italia per i css.

Comunque forse sarebbe stato meglio creare un ticket a parte per questo
