### ISSUE TITLE
Update User Page with Route Created from Booking Service

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#30]
US: #27 

### Descrizone:
Booking service deve andare a scrivere nella pagina dell'utente (#28) la rotta creata con la sua richiesta

**Comment by matteo-conti-97** [comment]
Aggiunto uno stub nel gateway api che mi ritorna dei percorsi fittizi come json, creato in main.py l'handler nel frontend per la gestione del caricamento della pagina con i percorsi relativi all'utente, in particolare vengono richiesti i percorsi tramite richiesta http al gateway api, modificato userRoutes.html in modo da generare dinamicamente la lista delle routes dell'utente.
