### ISSUE TITLE
Booking Service Persist The Received Route from 2-OPT

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#31]
US: #27 

### Descrizione:
Booking-service deve occuparsi di andare a salvare in persistenza la rotta ricevuta da 2-opt, inoltre deve decidere la "scadenza del percorso" e per questo ci sono varie scelte di design proposte in #95 ed il costo in euro dei vari itinerari (deve anche definire a priori delle cifre di cashback in base alle varie opzioni di affluenza effettiva al percorso, e poi eventualmente applicarla senza ricalcolarla in caso bisogna fare cashback?)

**Comment by matteo-conti-97** [comment]
@StefanAdrianHuma  @LucaFalasca ho aggiunto le query sul database per inserire un percorso (insert_route), per inserire un ordinamento (insert_order) e per inserire un itinerario_proposto (insert_it_proposed) inoltre nel db-service ho inserito la chiamata rpc (insert_route_info)  per eseguire una query che inserisce il percorso, tutti gli ordinamenti e tutti gli itinerari proposti, questo viene fatto dalla DAO del db-service tramite il metodo (insert_route_info) che avvia una transazione (con livello di isolamento repeatable read, non penso serva più alto perchè non facciamo select nella transazione) esegue l'insert del percorso ne prende l'id autoincrementale generato all'inserimento, scorre la lista degli order e li inserisce su db e poi scorre la lista degli itinerari proposti e li inserisce su db, infine fa la commit, se il tutto fallisce c'è il rollback gestito tramite eccezione.
