### ISSUE TITLE
Move mysql user db in docker container

### ISSUE THREAD

**Issue by matteo-conti-97** [LucaFalasca/Bus4You#32]
US #27

**Comment by matteo-conti-97** [comment]
Modificato il docker compose inserendo un container mysql che si basa su un dump presente nel volume, da verificare se quando si fa la build cancella le modifiche effettuate al db a runtime oppure no (e.g le insert)

**Comment by LucaFalasca** [comment]
è da chiudere questo ticket?

**Comment by matteo-conti-97** [comment]
Modificata la dao del database sostituendo le stored procedure con dei prepared statement altrimenti la query su db non veniva eseguita, verificato che le modifiche su database siano effettivamente persistenti quando si ribuilda il container

**Comment by matteo-conti-97** [comment]
Exception quando si eseguono stored procedure
