### ISSUE TITLE
Algorithm Does Not Consider User-Required Travel Time in Optimal Route Calculation

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#46]
L'algoritmo attuale non considera nel suo calcolo il travel time richiesto dagli utenti per il calcolo del percorso ottimale, ma solo quello totale. Bisogna aggiungere questo ulteriore filtro

**Comment by StefanAdrianHuma** [comment]
OK, il La struttura del Grafo Neo4J non dovrebbe variare ma il microservizio BookingService dovrà disporre di una nuova insert_booking che tenga presente di questi fatti (te la posso fare io).
Ad una rapida analisi non dovrebbe costituire un problema di compatibilità con le fermate renotate nell'altro modo, ma vi terrò aggiornati in caso contrario.

**Comment by LucaFalasca** [comment]
> OK, il La struttura del Grafo Neo4J non dovrebbe variare ma il microservizio BookingService dovrà disporre di una nuova insert_booking che tenga presente di questi fatti (te la posso fare io). Ad una rapida analisi non dovrebbe costituire un problema di compatibilità con le fermate renotate nell'altro modo, ma vi terrò aggiornati in caso contrario.

Nono, non dovrebbe cambiare niente, se non che quando si usa l'algoritmo gli si dovranno passare anche i valori mancanti

**Comment by LucaFalasca** [comment]
Abbiamo deciso di non dare più la possibilità all'utente di specificare il massimo tempo che ci vuole mettere. Semplicemente se l'utente non ritiene adatto il trvel time andrà a rifiurate l'itinerario proposto
