### ISSUE TITLE
Modification of the 2-opt algorithm to use topological sorting in an acyclic precedence graph

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#50]
US: #27

Descrizione:
Dato che c'è la necessità di controllare se il grafo delle precedenze è aciclico, l'algoritmo che fa ciò fornisce anche un ordinamento topologico che corrisponde ad una rotta ammissibile per il problema di ottimizzazione. Per questo motivo l'algoritmo 2-opt viene modificato in modo da chiedere in input la lista dei nodi invece che una rotta ammissibile di partenza, perchè essa verrà calcolata tramite l'algoritmo di ordinamento topologico

**Comment by LucaFalasca** [comment]
Ora per avviare l'algoritmo bisogna usare la procedure call "calculate_route" invece di "two_opt_multistart" e bisogna passargli due parametri:

1. Matrice delle distanze, è una matrice che rappresenta le distanze tra i nodi in termini di tempo
2.  un grafo orientato sottoforma di dizionario python che indica le relazioni di precedenza tra i nodi. Al contrario di prima ora bisogna inserire tutti i nodi nella pred_hash e non solo quelli che hanno dei vincoli. I nodi senza vincoli avranno associata una lista vuota.

Esempio:
`pred_hash = {"0": [1, 2], "1": [], "2": [4], "3": [4], "4": []}`

**Comment by StefanAdrianHuma** [comment]
OK, ricevuto!
