### ISSUE TITLE
Restructure SQL Database Schema to Accommodate Route and Reservation Information for Users

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#60]
US: #27

Descrizione:
Modificare lo schema del database SQL, in cui ci sono gli utenti al momento, in modo da supportare le informazioni riguardo ai percorsi e le prenotazioni associate agli utenti. 

Le query che ci serviranno saranno:
- Get/set delle prenotazioni confermate non ancora servite
- Get/set delle prenotazioni pending 
- Get/set delle prenotazioni confermate passate già servite
- Get/set delle prenotazioni rifiutate
- Get/set del percorso associato ad una prenotazione di un utente
- Get/set delle informazioni relative ad una prenotazione (orari, posizioni, ecc...)
- update dello stato da pending a confermato o rifiutato

Documentazione su come modificare lo schema del Database: [Progettazione Database Relazionale](https://github.com/LucaFalasca/Bus4You/wiki/Progettazione-Datase-Relazionale)

**Comment by matteo-conti-97** [comment]
Modificato il database secondo la nuova specifica, vedi Wiki per maggiori info, in caso di altre modifiche necessarie sul db aprire il file /mysql/userDb.sql e inserire a mano le modifiche (con molta attenzione) oppure aprire su mysql workbench il file userDb.mwb fare tramite ui le modifiche, fare il forward engineer del database, inserire eventuali righe dummy nelle tabelle e fare l'export del database includendo trigger, stored procedure etc come "self contained file"
