### ISSUE TITLE
Implement RabbitMQ for Connecting Booking Service with Notification Service

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#74]
US: #73

Descrizione:
Implementare RabbitMQ per connettere il booking service con il servizio di notifica. Creare un topic per utente probabilmente. Da definire il resto

**Comment by matteo-conti-97** [comment]
Aggiunto sul docker compose il necessario per tirare su un container contente rabbitMQ e un healtcheck per tale container, in modo che i servizi che devono utilizzare le code possano utilizzare il tag "depends on" per essere avviati dopo rabbitMQ
