### ISSUE TITLE
Update Booking Service to Notify All Users via RabbitMQ When Route is Ready

### ISSUE THREAD

**Issue by LucaFalasca** [LucaFalasca/Bus4You#76]
US: #73

Descrizione:
Aggiornare il booking service in modo tale una volta che ha un percorso pronto notifica tramite rabbitMQ ogni utente relativo a quel percorso

**Comment by matteo-conti-97** [comment]
Implementata la funzione che permette di collegarsi a rabbitMQ  e creare code e la funzione che permette di pubblicare su una coda. Non chiudo il ticket perchè la parte che va a pubblicare sulle code non è stata ancora implementata in quanto non è ancora stata implementata (immagino in altri ticket) la parte che gestisce quando viene generato un percorso da parte del makeRouteService, per sopperire ho creato una funzione di test nel booking service però l'ho commentata per non spammare mail ogni volta che si lancia il booking service.

**Comment by matteo-conti-97** [comment]
Aggiunta la parte che invia la notifica mail agli utenti dopo che booking service ha inserito le info sul percorso e tutti gli itinerari su db
